name: NekoCore
main: jp.kentan.minecraft.core.NekoCore
version: 1.14.39
author: ken_kentan
website: http://ken.kentan.jp

commands:
    neko:
        description: NekoCoreのヘルプを表示します。
        usage: /<command>
        permission: jp.kentan.minecraft.core
        permission-message: You don't have <permission>
    nk:
        description: NekoCoreのヘルプを表示します。
        usage: /<command>
        permission: jp.kentan.minecraft.core
        permission-message: You don't have <permission>
    vote:
        description: 投票サイトを表示します。
        usage: /<command>
        permission: jp.kentan.minecraft.core
        permission-message: You don't have <permission>
        