name: NekoCore
main: jp.kentan.minecraft.core
version: 0.0.1

commands:
 basic:
  description: This is a demo command.
  usage: /<command> [player]
  permission: tutorialplugin.basic
  permission-message: You don't have <permission>